version: '3'
services:
  webapp:
    image: nikitadockermain/try4imagemain
    ports:
      - "8089:8092"
    cpu_shares: 512
    mem_limit: 512m
    read_only: true
    security_opt:
      - "no-new-privileges=true"
    volumes:
      - "/root/tmp:/tmp"

  webapp2:
    image: nikitadockermain/devops-intimage
    ports:
      - "8090:8091"
    cpu_shares: 512
    mem_limit: 512m
    volumes:
      - "/var/lib/:/var/lib/games"

